import { ContractConfig } from "./types";

export const DEFAULT_CONFIG: ContractConfig = {
  performer: {
    name: "",
    citizenship: "",
    phone: "",
    email: "",
    address: "",
    postal_code: "n/a",
    dob: "",
    passport: "n/a",
    sin: "n/a",
    gst: "n/a",
    ubcp_number: "n/a",
    cavco: "n/a",
    bc_resident: false,
    us_citizen: false,
    us_resident: false,
    minor: false,
  },
  agent: {
    name: "n/a",
    agency: "n/a",
    agency_address_line1: "",
    agency_address_line2: "",
    cell: "n/a",
    email: "n/a",
    phone: "n/a",
  },
  deal: {
    role: "",
    role_number: "TBD",
    form_of_hire: "Daily",
    daily_rate: "",
    hourly_rate: "n/a",
    ot_15x: "n/a",
    ot_20x: "n/a",
    guaranteed_dates: "",
    num_days: "",
    outside_dates: "",
    per_diem: "n/a",
    credit: "APD",
    dressing_facility: "",
    location: "Vancouver, B.C.",
    transportation: "See Other Contractual Obligations below",
    other_contractual: "",
    salary_line: "",
  },
  memo_date: new Date().toISOString().split("T")[0],
};
